docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA06984.cns -o NA06984.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA06985.cns -o NA06985.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA06986.cns -o NA06986.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA06989.cns -o NA06989.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA06994.cns -o NA06994.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07000.cns -o NA07000.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07037.cns -o NA07037.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07048.cns -o NA07048.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07051.cns -o NA07051.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07056.cns -o NA07056.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07347.cns -o NA07347.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA07357.cns -o NA07357.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA10847.cns -o NA10847.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA10851.cns -o NA10851.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11829.cns -o NA11829.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11830.cns -o NA11830.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11831.cns -o NA11831.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11832.cns -o NA11832.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11840.cns -o NA11840.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11843.cns -o NA11843.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11881.cns -o NA11881.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11892.cns -o NA11892.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11893.cns -o NA11893.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11894.cns -o NA11894.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11918.cns -o NA11918.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11919.cns -o NA11919.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11920.cns -o NA11920.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11930.cns -o NA11930.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11931.cns -o NA11931.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11932.cns -o NA11932.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11933.cns -o NA11933.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11992.cns -o NA11992.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11994.cns -o NA11994.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA11995.cns -o NA11995.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12003.cns -o NA12003.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12004.cns -o NA12004.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12005.cns -o NA12005.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12006.cns -o NA12006.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12043.cns -o NA12043.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12044.cns -o NA12044.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12045.cns -o NA12045.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12046.cns -o NA12046.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12058.cns -o NA12058.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12144.cns -o NA12144.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12154.cns -o NA12154.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12155.cns -o NA12155.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12156.cns -o NA12156.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12234.cns -o NA12234.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12249.cns -o NA12249.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12272.cns -o NA12272.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12273.cns -o NA12273.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12275.cns -o NA12275.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12282.cns -o NA12282.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12283.cns -o NA12283.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12286.cns -o NA12286.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12287.cns -o NA12287.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12340.cns -o NA12340.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12341.cns -o NA12341.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12342.cns -o NA12342.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12347.cns -o NA12347.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12348.cns -o NA12348.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12383.cns -o NA12383.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12399.cns -o NA12399.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12400.cns -o NA12400.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12413.cns -o NA12413.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12414.cns -o NA12414.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12489.cns -o NA12489.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12546.cns -o NA12546.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12716.cns -o NA12716.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12717.cns -o NA12717.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12718.cns -o NA12718.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12748.cns -o NA12748.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12749.cns -o NA12749.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12750.cns -o NA12750.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12751.cns -o NA12751.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12760.cns -o NA12760.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12761.cns -o NA12761.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12762.cns -o NA12762.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12763.cns -o NA12763.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12775.cns -o NA12775.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12776.cns -o NA12776.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12777.cns -o NA12777.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12778.cns -o NA12778.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12812.cns -o NA12812.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12813.cns -o NA12813.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12814.cns -o NA12814.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12815.cns -o NA12815.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12827.cns -o NA12827.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12828.cns -o NA12828.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12829.cns -o NA12829.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12830.cns -o NA12830.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12842.cns -o NA12842.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12843.cns -o NA12843.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12872.cns -o NA12872.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12873.cns -o NA12873.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12874.cns -o NA12874.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12878.cns -o NA12878.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12889.cns -o NA12889.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA12890.cns -o NA12890.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18486.cns -o NA18486.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18488.cns -o NA18488.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18489.cns -o NA18489.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18498.cns -o NA18498.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18499.cns -o NA18499.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18501.cns -o NA18501.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18502.cns -o NA18502.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18504.cns -o NA18504.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18505.cns -o NA18505.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18507.cns -o NA18507.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18508.cns -o NA18508.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18510.cns -o NA18510.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18511.cns -o NA18511.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18516.cns -o NA18516.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18517.cns -o NA18517.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18519.cns -o NA18519.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18520.cns -o NA18520.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18522.cns -o NA18522.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18523.cns -o NA18523.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18525.cns -o NA18525.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18526.cns -o NA18526.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18528.cns -o NA18528.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18530.cns -o NA18530.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18531.cns -o NA18531.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18532.cns -o NA18532.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18533.cns -o NA18533.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18534.cns -o NA18534.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18535.cns -o NA18535.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18536.cns -o NA18536.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18537.cns -o NA18537.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18538.cns -o NA18538.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18539.cns -o NA18539.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18541.cns -o NA18541.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18542.cns -o NA18542.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18543.cns -o NA18543.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18544.cns -o NA18544.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18545.cns -o NA18545.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18546.cns -o NA18546.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18547.cns -o NA18547.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18548.cns -o NA18548.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18549.cns -o NA18549.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18550.cns -o NA18550.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18552.cns -o NA18552.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18553.cns -o NA18553.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18555.cns -o NA18555.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18557.cns -o NA18557.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18558.cns -o NA18558.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18559.cns -o NA18559.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18560.cns -o NA18560.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18561.cns -o NA18561.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18562.cns -o NA18562.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18563.cns -o NA18563.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18564.cns -o NA18564.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18565.cns -o NA18565.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18566.cns -o NA18566.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18567.cns -o NA18567.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18570.cns -o NA18570.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18571.cns -o NA18571.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18572.cns -o NA18572.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18573.cns -o NA18573.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18574.cns -o NA18574.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18577.cns -o NA18577.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18579.cns -o NA18579.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18582.cns -o NA18582.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18591.cns -o NA18591.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18592.cns -o NA18592.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18593.cns -o NA18593.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18595.cns -o NA18595.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18596.cns -o NA18596.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18597.cns -o NA18597.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18599.cns -o NA18599.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18602.cns -o NA18602.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18603.cns -o NA18603.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18605.cns -o NA18605.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18606.cns -o NA18606.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18608.cns -o NA18608.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18609.cns -o NA18609.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18610.cns -o NA18610.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18611.cns -o NA18611.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18612.cns -o NA18612.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18613.cns -o NA18613.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18614.cns -o NA18614.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18615.cns -o NA18615.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18616.cns -o NA18616.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18617.cns -o NA18617.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18618.cns -o NA18618.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18619.cns -o NA18619.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18620.cns -o NA18620.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18621.cns -o NA18621.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18622.cns -o NA18622.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18623.cns -o NA18623.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18624.cns -o NA18624.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18625.cns -o NA18625.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18626.cns -o NA18626.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18627.cns -o NA18627.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18628.cns -o NA18628.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18629.cns -o NA18629.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18630.cns -o NA18630.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18631.cns -o NA18631.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18632.cns -o NA18632.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18633.cns -o NA18633.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18634.cns -o NA18634.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18635.cns -o NA18635.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18636.cns -o NA18636.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18637.cns -o NA18637.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18638.cns -o NA18638.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18639.cns -o NA18639.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18640.cns -o NA18640.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18641.cns -o NA18641.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18642.cns -o NA18642.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18643.cns -o NA18643.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18644.cns -o NA18644.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18645.cns -o NA18645.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18646.cns -o NA18646.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18647.cns -o NA18647.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18648.cns -o NA18648.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18740.cns -o NA18740.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18745.cns -o NA18745.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18747.cns -o NA18747.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18748.cns -o NA18748.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18749.cns -o NA18749.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18757.cns -o NA18757.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18853.cns -o NA18853.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18856.cns -o NA18856.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18858.cns -o NA18858.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18861.cns -o NA18861.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18864.cns -o NA18864.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18865.cns -o NA18865.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18867.cns -o NA18867.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18868.cns -o NA18868.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18870.cns -o NA18870.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18871.cns -o NA18871.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18873.cns -o NA18873.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18874.cns -o NA18874.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18876.cns -o NA18876.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18877.cns -o NA18877.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18878.cns -o NA18878.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18879.cns -o NA18879.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18881.cns -o NA18881.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18907.cns -o NA18907.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18908.cns -o NA18908.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18909.cns -o NA18909.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18910.cns -o NA18910.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18912.cns -o NA18912.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18915.cns -o NA18915.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18916.cns -o NA18916.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18917.cns -o NA18917.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18923.cns -o NA18923.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18924.cns -o NA18924.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18933.cns -o NA18933.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18934.cns -o NA18934.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18939.cns -o NA18939.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18940.cns -o NA18940.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18941.cns -o NA18941.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18942.cns -o NA18942.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18943.cns -o NA18943.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18944.cns -o NA18944.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18945.cns -o NA18945.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18946.cns -o NA18946.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18947.cns -o NA18947.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18948.cns -o NA18948.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18949.cns -o NA18949.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18950.cns -o NA18950.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18951.cns -o NA18951.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18952.cns -o NA18952.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18953.cns -o NA18953.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18954.cns -o NA18954.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18956.cns -o NA18956.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18957.cns -o NA18957.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18959.cns -o NA18959.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18960.cns -o NA18960.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18961.cns -o NA18961.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18962.cns -o NA18962.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18963.cns -o NA18963.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18964.cns -o NA18964.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18965.cns -o NA18965.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18966.cns -o NA18966.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18967.cns -o NA18967.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18968.cns -o NA18968.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18969.cns -o NA18969.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18970.cns -o NA18970.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18971.cns -o NA18971.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18972.cns -o NA18972.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18973.cns -o NA18973.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18974.cns -o NA18974.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18975.cns -o NA18975.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18976.cns -o NA18976.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18977.cns -o NA18977.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18978.cns -o NA18978.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18979.cns -o NA18979.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18980.cns -o NA18980.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18981.cns -o NA18981.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18982.cns -o NA18982.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18983.cns -o NA18983.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18984.cns -o NA18984.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18985.cns -o NA18985.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18986.cns -o NA18986.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18987.cns -o NA18987.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18988.cns -o NA18988.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18989.cns -o NA18989.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18990.cns -o NA18990.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18991.cns -o NA18991.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18992.cns -o NA18992.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18993.cns -o NA18993.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18994.cns -o NA18994.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18995.cns -o NA18995.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18997.cns -o NA18997.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18998.cns -o NA18998.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA18999.cns -o NA18999.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19000.cns -o NA19000.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19001.cns -o NA19001.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19002.cns -o NA19002.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19003.cns -o NA19003.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19004.cns -o NA19004.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19005.cns -o NA19005.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19006.cns -o NA19006.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19007.cns -o NA19007.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19009.cns -o NA19009.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19010.cns -o NA19010.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19011.cns -o NA19011.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19012.cns -o NA19012.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19017.cns -o NA19017.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19019.cns -o NA19019.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19020.cns -o NA19020.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19023.cns -o NA19023.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19024.cns -o NA19024.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19025.cns -o NA19025.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19026.cns -o NA19026.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19027.cns -o NA19027.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19028.cns -o NA19028.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19030.cns -o NA19030.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19031.cns -o NA19031.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19035.cns -o NA19035.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19036.cns -o NA19036.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19037.cns -o NA19037.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19038.cns -o NA19038.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19041.cns -o NA19041.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19042.cns -o NA19042.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19043.cns -o NA19043.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19054.cns -o NA19054.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19055.cns -o NA19055.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19056.cns -o NA19056.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19057.cns -o NA19057.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19058.cns -o NA19058.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19059.cns -o NA19059.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19060.cns -o NA19060.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19062.cns -o NA19062.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19063.cns -o NA19063.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19064.cns -o NA19064.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19065.cns -o NA19065.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19066.cns -o NA19066.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19067.cns -o NA19067.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19068.cns -o NA19068.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19070.cns -o NA19070.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19072.cns -o NA19072.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19074.cns -o NA19074.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19075.cns -o NA19075.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19076.cns -o NA19076.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19077.cns -o NA19077.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19078.cns -o NA19078.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19079.cns -o NA19079.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19080.cns -o NA19080.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19081.cns -o NA19081.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19082.cns -o NA19082.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19083.cns -o NA19083.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19084.cns -o NA19084.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19085.cns -o NA19085.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19086.cns -o NA19086.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19087.cns -o NA19087.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19088.cns -o NA19088.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19089.cns -o NA19089.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19090.cns -o NA19090.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19091.cns -o NA19091.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19092.cns -o NA19092.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19093.cns -o NA19093.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19095.cns -o NA19095.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19096.cns -o NA19096.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19098.cns -o NA19098.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19099.cns -o NA19099.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19102.cns -o NA19102.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19107.cns -o NA19107.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19108.cns -o NA19108.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19113.cns -o NA19113.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19114.cns -o NA19114.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19116.cns -o NA19116.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19117.cns -o NA19117.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19118.cns -o NA19118.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19119.cns -o NA19119.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19121.cns -o NA19121.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19129.cns -o NA19129.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19130.cns -o NA19130.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19131.cns -o NA19131.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19137.cns -o NA19137.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19138.cns -o NA19138.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19141.cns -o NA19141.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19143.cns -o NA19143.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19144.cns -o NA19144.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19146.cns -o NA19146.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19147.cns -o NA19147.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19149.cns -o NA19149.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19152.cns -o NA19152.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19153.cns -o NA19153.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19159.cns -o NA19159.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19160.cns -o NA19160.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19171.cns -o NA19171.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19172.cns -o NA19172.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19175.cns -o NA19175.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19184.cns -o NA19184.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19185.cns -o NA19185.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19189.cns -o NA19189.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19190.cns -o NA19190.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19197.cns -o NA19197.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19198.cns -o NA19198.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19200.cns -o NA19200.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19201.cns -o NA19201.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19204.cns -o NA19204.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19206.cns -o NA19206.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19207.cns -o NA19207.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19209.cns -o NA19209.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19210.cns -o NA19210.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19213.cns -o NA19213.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19214.cns -o NA19214.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19222.cns -o NA19222.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19223.cns -o NA19223.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19225.cns -o NA19225.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19235.cns -o NA19235.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19236.cns -o NA19236.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19238.cns -o NA19238.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19239.cns -o NA19239.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19240.cns -o NA19240.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19247.cns -o NA19247.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19248.cns -o NA19248.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19256.cns -o NA19256.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19257.cns -o NA19257.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19307.cns -o NA19307.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19308.cns -o NA19308.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19309.cns -o NA19309.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19310.cns -o NA19310.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19311.cns -o NA19311.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19312.cns -o NA19312.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19313.cns -o NA19313.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19314.cns -o NA19314.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19315.cns -o NA19315.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19316.cns -o NA19316.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19317.cns -o NA19317.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19318.cns -o NA19318.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19319.cns -o NA19319.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19320.cns -o NA19320.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19321.cns -o NA19321.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19323.cns -o NA19323.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19324.cns -o NA19324.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19327.cns -o NA19327.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19328.cns -o NA19328.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19331.cns -o NA19331.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19332.cns -o NA19332.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19334.cns -o NA19334.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19338.cns -o NA19338.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19346.cns -o NA19346.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19347.cns -o NA19347.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19350.cns -o NA19350.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19351.cns -o NA19351.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19355.cns -o NA19355.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19360.cns -o NA19360.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19372.cns -o NA19372.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19374.cns -o NA19374.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19375.cns -o NA19375.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19376.cns -o NA19376.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19377.cns -o NA19377.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19378.cns -o NA19378.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19379.cns -o NA19379.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19380.cns -o NA19380.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19383.cns -o NA19383.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19384.cns -o NA19384.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19385.cns -o NA19385.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19390.cns -o NA19390.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19391.cns -o NA19391.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19393.cns -o NA19393.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19394.cns -o NA19394.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19395.cns -o NA19395.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19397.cns -o NA19397.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19399.cns -o NA19399.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19401.cns -o NA19401.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19403.cns -o NA19403.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19404.cns -o NA19404.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19428.cns -o NA19428.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19429.cns -o NA19429.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19430.cns -o NA19430.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19431.cns -o NA19431.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19434.cns -o NA19434.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19435.cns -o NA19435.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19436.cns -o NA19436.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19437.cns -o NA19437.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19438.cns -o NA19438.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19439.cns -o NA19439.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19440.cns -o NA19440.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19443.cns -o NA19443.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19445.cns -o NA19445.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19446.cns -o NA19446.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19448.cns -o NA19448.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19449.cns -o NA19449.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19451.cns -o NA19451.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19452.cns -o NA19452.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19454.cns -o NA19454.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19455.cns -o NA19455.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19456.cns -o NA19456.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19457.cns -o NA19457.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19461.cns -o NA19461.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19462.cns -o NA19462.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19463.cns -o NA19463.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19466.cns -o NA19466.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19467.cns -o NA19467.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19468.cns -o NA19468.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19471.cns -o NA19471.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19472.cns -o NA19472.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19473.cns -o NA19473.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19474.cns -o NA19474.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19475.cns -o NA19475.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19625.cns -o NA19625.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19648.cns -o NA19648.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19649.cns -o NA19649.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19651.cns -o NA19651.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19652.cns -o NA19652.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19654.cns -o NA19654.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19655.cns -o NA19655.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19657.cns -o NA19657.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19658.cns -o NA19658.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19660.cns -o NA19660.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19661.cns -o NA19661.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19663.cns -o NA19663.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19664.cns -o NA19664.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19669.cns -o NA19669.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19670.cns -o NA19670.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19675.cns -o NA19675.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19676.cns -o NA19676.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19678.cns -o NA19678.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19679.cns -o NA19679.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19681.cns -o NA19681.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19682.cns -o NA19682.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19684.cns -o NA19684.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19685.cns -o NA19685.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19700.cns -o NA19700.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19701.cns -o NA19701.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19703.cns -o NA19703.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19704.cns -o NA19704.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19707.cns -o NA19707.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19711.cns -o NA19711.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19712.cns -o NA19712.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19713.cns -o NA19713.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19716.cns -o NA19716.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19717.cns -o NA19717.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19719.cns -o NA19719.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19720.cns -o NA19720.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19722.cns -o NA19722.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19723.cns -o NA19723.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19725.cns -o NA19725.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19726.cns -o NA19726.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19728.cns -o NA19728.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19729.cns -o NA19729.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19731.cns -o NA19731.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19732.cns -o NA19732.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19734.cns -o NA19734.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19735.cns -o NA19735.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19740.cns -o NA19740.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19741.cns -o NA19741.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19746.cns -o NA19746.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19747.cns -o NA19747.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19749.cns -o NA19749.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19750.cns -o NA19750.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19752.cns -o NA19752.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19755.cns -o NA19755.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19756.cns -o NA19756.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19758.cns -o NA19758.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19759.cns -o NA19759.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19761.cns -o NA19761.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19762.cns -o NA19762.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19764.cns -o NA19764.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19770.cns -o NA19770.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19771.cns -o NA19771.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19773.cns -o NA19773.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19774.cns -o NA19774.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19776.cns -o NA19776.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19777.cns -o NA19777.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19779.cns -o NA19779.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19780.cns -o NA19780.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19782.cns -o NA19782.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19783.cns -o NA19783.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19785.cns -o NA19785.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19786.cns -o NA19786.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19788.cns -o NA19788.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19789.cns -o NA19789.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19792.cns -o NA19792.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19794.cns -o NA19794.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19795.cns -o NA19795.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19818.cns -o NA19818.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19819.cns -o NA19819.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19834.cns -o NA19834.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19835.cns -o NA19835.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19900.cns -o NA19900.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19901.cns -o NA19901.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19904.cns -o NA19904.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19908.cns -o NA19908.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19909.cns -o NA19909.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19913.cns -o NA19913.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19914.cns -o NA19914.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19916.cns -o NA19916.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19917.cns -o NA19917.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19920.cns -o NA19920.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19921.cns -o NA19921.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19922.cns -o NA19922.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19923.cns -o NA19923.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19982.cns -o NA19982.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19984.cns -o NA19984.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA19985.cns -o NA19985.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20126.cns -o NA20126.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20127.cns -o NA20127.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20274.cns -o NA20274.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20276.cns -o NA20276.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20278.cns -o NA20278.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20281.cns -o NA20281.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20282.cns -o NA20282.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20287.cns -o NA20287.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20289.cns -o NA20289.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20291.cns -o NA20291.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20294.cns -o NA20294.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20296.cns -o NA20296.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20298.cns -o NA20298.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20299.cns -o NA20299.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20314.cns -o NA20314.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20317.cns -o NA20317.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20318.cns -o NA20318.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20320.cns -o NA20320.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20321.cns -o NA20321.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20322.cns -o NA20322.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20332.cns -o NA20332.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20334.cns -o NA20334.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20336.cns -o NA20336.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20339.cns -o NA20339.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20340.cns -o NA20340.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20341.cns -o NA20341.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20342.cns -o NA20342.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20344.cns -o NA20344.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20346.cns -o NA20346.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20348.cns -o NA20348.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20351.cns -o NA20351.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20355.cns -o NA20355.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20356.cns -o NA20356.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20357.cns -o NA20357.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20359.cns -o NA20359.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20362.cns -o NA20362.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20412.cns -o NA20412.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20502.cns -o NA20502.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20503.cns -o NA20503.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20504.cns -o NA20504.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20505.cns -o NA20505.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20506.cns -o NA20506.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20507.cns -o NA20507.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20508.cns -o NA20508.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20509.cns -o NA20509.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20510.cns -o NA20510.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20511.cns -o NA20511.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20512.cns -o NA20512.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20513.cns -o NA20513.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20514.cns -o NA20514.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20515.cns -o NA20515.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20516.cns -o NA20516.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20517.cns -o NA20517.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20518.cns -o NA20518.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20519.cns -o NA20519.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20520.cns -o NA20520.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20521.cns -o NA20521.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20522.cns -o NA20522.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20524.cns -o NA20524.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20525.cns -o NA20525.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20526.cns -o NA20526.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20527.cns -o NA20527.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20528.cns -o NA20528.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20529.cns -o NA20529.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20530.cns -o NA20530.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20531.cns -o NA20531.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20532.cns -o NA20532.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20533.cns -o NA20533.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20534.cns -o NA20534.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20535.cns -o NA20535.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20536.cns -o NA20536.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20538.cns -o NA20538.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20539.cns -o NA20539.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20540.cns -o NA20540.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20541.cns -o NA20541.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20542.cns -o NA20542.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20543.cns -o NA20543.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20544.cns -o NA20544.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20581.cns -o NA20581.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20582.cns -o NA20582.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20585.cns -o NA20585.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20586.cns -o NA20586.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20587.cns -o NA20587.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20588.cns -o NA20588.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20589.cns -o NA20589.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20752.cns -o NA20752.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20753.cns -o NA20753.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20754.cns -o NA20754.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20755.cns -o NA20755.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20756.cns -o NA20756.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20757.cns -o NA20757.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20758.cns -o NA20758.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20759.cns -o NA20759.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20760.cns -o NA20760.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20761.cns -o NA20761.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20762.cns -o NA20762.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20763.cns -o NA20763.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20764.cns -o NA20764.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20765.cns -o NA20765.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20766.cns -o NA20766.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20767.cns -o NA20767.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20768.cns -o NA20768.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20769.cns -o NA20769.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20770.cns -o NA20770.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20771.cns -o NA20771.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20772.cns -o NA20772.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20773.cns -o NA20773.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20774.cns -o NA20774.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20775.cns -o NA20775.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20778.cns -o NA20778.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20783.cns -o NA20783.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20785.cns -o NA20785.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20786.cns -o NA20786.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20787.cns -o NA20787.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20790.cns -o NA20790.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20792.cns -o NA20792.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20795.cns -o NA20795.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20796.cns -o NA20796.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20797.cns -o NA20797.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20798.cns -o NA20798.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20799.cns -o NA20799.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20802.cns -o NA20802.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20803.cns -o NA20803.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20804.cns -o NA20804.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20805.cns -o NA20805.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20806.cns -o NA20806.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20807.cns -o NA20807.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20808.cns -o NA20808.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20809.cns -o NA20809.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20810.cns -o NA20810.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20811.cns -o NA20811.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20812.cns -o NA20812.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20813.cns -o NA20813.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20814.cns -o NA20814.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20815.cns -o NA20815.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20818.cns -o NA20818.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20819.cns -o NA20819.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20821.cns -o NA20821.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20822.cns -o NA20822.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20826.cns -o NA20826.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20827.cns -o NA20827.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20828.cns -o NA20828.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20832.cns -o NA20832.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20845.cns -o NA20845.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20846.cns -o NA20846.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20847.cns -o NA20847.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20849.cns -o NA20849.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20850.cns -o NA20850.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20851.cns -o NA20851.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20852.cns -o NA20852.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20853.cns -o NA20853.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20854.cns -o NA20854.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20856.cns -o NA20856.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20858.cns -o NA20858.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20859.cns -o NA20859.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20861.cns -o NA20861.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20862.cns -o NA20862.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20863.cns -o NA20863.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20864.cns -o NA20864.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20866.cns -o NA20866.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20867.cns -o NA20867.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20868.cns -o NA20868.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20869.cns -o NA20869.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20870.cns -o NA20870.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20871.cns -o NA20871.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20872.cns -o NA20872.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20874.cns -o NA20874.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20875.cns -o NA20875.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20876.cns -o NA20876.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20877.cns -o NA20877.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20878.cns -o NA20878.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20881.cns -o NA20881.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20882.cns -o NA20882.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20884.cns -o NA20884.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20885.cns -o NA20885.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20886.cns -o NA20886.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20887.cns -o NA20887.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20888.cns -o NA20888.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20889.cns -o NA20889.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20890.cns -o NA20890.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20891.cns -o NA20891.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20892.cns -o NA20892.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20893.cns -o NA20893.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20894.cns -o NA20894.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20895.cns -o NA20895.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20896.cns -o NA20896.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20897.cns -o NA20897.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20898.cns -o NA20898.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20899.cns -o NA20899.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20900.cns -o NA20900.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20901.cns -o NA20901.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20902.cns -o NA20902.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20903.cns -o NA20903.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20904.cns -o NA20904.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20905.cns -o NA20905.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20906.cns -o NA20906.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20908.cns -o NA20908.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20910.cns -o NA20910.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA20911.cns -o NA20911.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21086.cns -o NA21086.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21087.cns -o NA21087.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21088.cns -o NA21088.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21089.cns -o NA21089.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21090.cns -o NA21090.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21091.cns -o NA21091.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21092.cns -o NA21092.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21093.cns -o NA21093.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21094.cns -o NA21094.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21095.cns -o NA21095.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21097.cns -o NA21097.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21098.cns -o NA21098.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21099.cns -o NA21099.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21100.cns -o NA21100.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21101.cns -o NA21101.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21102.cns -o NA21102.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21103.cns -o NA21103.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21104.cns -o NA21104.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21105.cns -o NA21105.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21106.cns -o NA21106.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21107.cns -o NA21107.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21108.cns -o NA21108.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21109.cns -o NA21109.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21110.cns -o NA21110.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21111.cns -o NA21111.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21112.cns -o NA21112.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21113.cns -o NA21113.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21114.cns -o NA21114.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21115.cns -o NA21115.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21116.cns -o NA21116.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21117.cns -o NA21117.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21118.cns -o NA21118.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21119.cns -o NA21119.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21120.cns -o NA21120.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21122.cns -o NA21122.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21123.cns -o NA21123.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21124.cns -o NA21124.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21125.cns -o NA21125.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21126.cns -o NA21126.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21127.cns -o NA21127.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21128.cns -o NA21128.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21129.cns -o NA21129.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21130.cns -o NA21130.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21133.cns -o NA21133.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21135.cns -o NA21135.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21137.cns -o NA21137.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21141.cns -o NA21141.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21142.cns -o NA21142.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21143.cns -o NA21143.call.cns
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py call NA21144.cns -o NA21144.call.cns
