docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA06984.cnr -o NA06984.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA06985.cnr -o NA06985.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA06986.cnr -o NA06986.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA06989.cnr -o NA06989.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA06994.cnr -o NA06994.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07000.cnr -o NA07000.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07037.cnr -o NA07037.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07048.cnr -o NA07048.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07051.cnr -o NA07051.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07056.cnr -o NA07056.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07347.cnr -o NA07347.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA07357.cnr -o NA07357.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA10847.cnr -o NA10847.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA10851.cnr -o NA10851.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11829.cnr -o NA11829.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11830.cnr -o NA11830.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11831.cnr -o NA11831.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11832.cnr -o NA11832.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11840.cnr -o NA11840.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11843.cnr -o NA11843.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11881.cnr -o NA11881.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11892.cnr -o NA11892.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11893.cnr -o NA11893.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11894.cnr -o NA11894.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11918.cnr -o NA11918.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11919.cnr -o NA11919.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11920.cnr -o NA11920.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11930.cnr -o NA11930.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11931.cnr -o NA11931.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11932.cnr -o NA11932.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11933.cnr -o NA11933.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11992.cnr -o NA11992.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11994.cnr -o NA11994.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA11995.cnr -o NA11995.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12003.cnr -o NA12003.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12004.cnr -o NA12004.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12005.cnr -o NA12005.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12006.cnr -o NA12006.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12043.cnr -o NA12043.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12044.cnr -o NA12044.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12045.cnr -o NA12045.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12046.cnr -o NA12046.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12058.cnr -o NA12058.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12144.cnr -o NA12144.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12154.cnr -o NA12154.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12155.cnr -o NA12155.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12156.cnr -o NA12156.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12234.cnr -o NA12234.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12249.cnr -o NA12249.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12272.cnr -o NA12272.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12273.cnr -o NA12273.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12275.cnr -o NA12275.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12282.cnr -o NA12282.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12283.cnr -o NA12283.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12286.cnr -o NA12286.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12287.cnr -o NA12287.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12340.cnr -o NA12340.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12341.cnr -o NA12341.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12342.cnr -o NA12342.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12347.cnr -o NA12347.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12348.cnr -o NA12348.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12383.cnr -o NA12383.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12399.cnr -o NA12399.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12400.cnr -o NA12400.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12413.cnr -o NA12413.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12414.cnr -o NA12414.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12489.cnr -o NA12489.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12546.cnr -o NA12546.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12716.cnr -o NA12716.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12717.cnr -o NA12717.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12718.cnr -o NA12718.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12748.cnr -o NA12748.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12749.cnr -o NA12749.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12750.cnr -o NA12750.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12751.cnr -o NA12751.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12760.cnr -o NA12760.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12761.cnr -o NA12761.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12762.cnr -o NA12762.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12763.cnr -o NA12763.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12775.cnr -o NA12775.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12776.cnr -o NA12776.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12777.cnr -o NA12777.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12778.cnr -o NA12778.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12812.cnr -o NA12812.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12813.cnr -o NA12813.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12814.cnr -o NA12814.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12815.cnr -o NA12815.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12827.cnr -o NA12827.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12828.cnr -o NA12828.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12829.cnr -o NA12829.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12830.cnr -o NA12830.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12842.cnr -o NA12842.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12843.cnr -o NA12843.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12872.cnr -o NA12872.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12873.cnr -o NA12873.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12874.cnr -o NA12874.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12878.cnr -o NA12878.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12889.cnr -o NA12889.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA12890.cnr -o NA12890.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18486.cnr -o NA18486.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18488.cnr -o NA18488.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18489.cnr -o NA18489.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18498.cnr -o NA18498.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18499.cnr -o NA18499.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18501.cnr -o NA18501.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18502.cnr -o NA18502.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18504.cnr -o NA18504.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18505.cnr -o NA18505.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18507.cnr -o NA18507.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18508.cnr -o NA18508.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18510.cnr -o NA18510.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18511.cnr -o NA18511.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18516.cnr -o NA18516.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18517.cnr -o NA18517.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18519.cnr -o NA18519.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18520.cnr -o NA18520.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18522.cnr -o NA18522.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18523.cnr -o NA18523.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18525.cnr -o NA18525.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18526.cnr -o NA18526.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18528.cnr -o NA18528.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18530.cnr -o NA18530.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18531.cnr -o NA18531.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18532.cnr -o NA18532.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18533.cnr -o NA18533.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18534.cnr -o NA18534.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18535.cnr -o NA18535.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18536.cnr -o NA18536.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18537.cnr -o NA18537.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18538.cnr -o NA18538.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18539.cnr -o NA18539.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18541.cnr -o NA18541.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18542.cnr -o NA18542.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18543.cnr -o NA18543.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18544.cnr -o NA18544.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18545.cnr -o NA18545.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18546.cnr -o NA18546.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18547.cnr -o NA18547.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18548.cnr -o NA18548.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18549.cnr -o NA18549.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18550.cnr -o NA18550.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18552.cnr -o NA18552.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18553.cnr -o NA18553.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18555.cnr -o NA18555.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18557.cnr -o NA18557.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18558.cnr -o NA18558.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18559.cnr -o NA18559.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18560.cnr -o NA18560.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18561.cnr -o NA18561.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18562.cnr -o NA18562.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18563.cnr -o NA18563.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18564.cnr -o NA18564.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18565.cnr -o NA18565.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18566.cnr -o NA18566.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18567.cnr -o NA18567.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18570.cnr -o NA18570.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18571.cnr -o NA18571.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18572.cnr -o NA18572.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18573.cnr -o NA18573.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18574.cnr -o NA18574.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18577.cnr -o NA18577.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18579.cnr -o NA18579.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18582.cnr -o NA18582.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18591.cnr -o NA18591.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18592.cnr -o NA18592.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18593.cnr -o NA18593.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18595.cnr -o NA18595.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18596.cnr -o NA18596.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18597.cnr -o NA18597.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18599.cnr -o NA18599.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18602.cnr -o NA18602.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18603.cnr -o NA18603.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18605.cnr -o NA18605.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18606.cnr -o NA18606.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18608.cnr -o NA18608.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18609.cnr -o NA18609.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18610.cnr -o NA18610.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18611.cnr -o NA18611.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18612.cnr -o NA18612.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18613.cnr -o NA18613.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18614.cnr -o NA18614.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18615.cnr -o NA18615.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18616.cnr -o NA18616.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18617.cnr -o NA18617.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18618.cnr -o NA18618.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18619.cnr -o NA18619.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18620.cnr -o NA18620.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18621.cnr -o NA18621.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18622.cnr -o NA18622.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18623.cnr -o NA18623.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18624.cnr -o NA18624.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18625.cnr -o NA18625.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18626.cnr -o NA18626.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18627.cnr -o NA18627.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18628.cnr -o NA18628.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18629.cnr -o NA18629.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18630.cnr -o NA18630.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18631.cnr -o NA18631.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18632.cnr -o NA18632.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18633.cnr -o NA18633.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18634.cnr -o NA18634.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18635.cnr -o NA18635.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18636.cnr -o NA18636.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18637.cnr -o NA18637.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18638.cnr -o NA18638.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18639.cnr -o NA18639.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18640.cnr -o NA18640.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18641.cnr -o NA18641.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18642.cnr -o NA18642.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18643.cnr -o NA18643.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18644.cnr -o NA18644.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18645.cnr -o NA18645.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18646.cnr -o NA18646.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18647.cnr -o NA18647.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18648.cnr -o NA18648.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18740.cnr -o NA18740.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18745.cnr -o NA18745.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18747.cnr -o NA18747.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18748.cnr -o NA18748.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18749.cnr -o NA18749.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18757.cnr -o NA18757.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18853.cnr -o NA18853.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18856.cnr -o NA18856.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18858.cnr -o NA18858.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18861.cnr -o NA18861.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18864.cnr -o NA18864.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18865.cnr -o NA18865.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18867.cnr -o NA18867.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18868.cnr -o NA18868.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18870.cnr -o NA18870.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18871.cnr -o NA18871.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18873.cnr -o NA18873.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18874.cnr -o NA18874.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18876.cnr -o NA18876.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18877.cnr -o NA18877.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18878.cnr -o NA18878.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18879.cnr -o NA18879.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18881.cnr -o NA18881.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18907.cnr -o NA18907.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18908.cnr -o NA18908.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18909.cnr -o NA18909.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18910.cnr -o NA18910.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18912.cnr -o NA18912.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18915.cnr -o NA18915.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18916.cnr -o NA18916.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18917.cnr -o NA18917.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18923.cnr -o NA18923.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18924.cnr -o NA18924.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18933.cnr -o NA18933.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18934.cnr -o NA18934.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18939.cnr -o NA18939.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18940.cnr -o NA18940.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18941.cnr -o NA18941.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18942.cnr -o NA18942.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18943.cnr -o NA18943.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18944.cnr -o NA18944.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18945.cnr -o NA18945.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18946.cnr -o NA18946.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18947.cnr -o NA18947.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18948.cnr -o NA18948.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18949.cnr -o NA18949.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18950.cnr -o NA18950.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18951.cnr -o NA18951.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18952.cnr -o NA18952.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18953.cnr -o NA18953.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18954.cnr -o NA18954.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18956.cnr -o NA18956.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18957.cnr -o NA18957.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18959.cnr -o NA18959.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18960.cnr -o NA18960.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18961.cnr -o NA18961.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18962.cnr -o NA18962.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18963.cnr -o NA18963.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18964.cnr -o NA18964.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18965.cnr -o NA18965.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18966.cnr -o NA18966.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18967.cnr -o NA18967.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18968.cnr -o NA18968.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18969.cnr -o NA18969.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18970.cnr -o NA18970.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18971.cnr -o NA18971.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18972.cnr -o NA18972.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18973.cnr -o NA18973.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18974.cnr -o NA18974.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18975.cnr -o NA18975.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18976.cnr -o NA18976.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18977.cnr -o NA18977.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18978.cnr -o NA18978.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18979.cnr -o NA18979.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18980.cnr -o NA18980.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18981.cnr -o NA18981.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18982.cnr -o NA18982.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18983.cnr -o NA18983.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18984.cnr -o NA18984.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18985.cnr -o NA18985.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18986.cnr -o NA18986.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18987.cnr -o NA18987.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18988.cnr -o NA18988.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18989.cnr -o NA18989.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18990.cnr -o NA18990.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18991.cnr -o NA18991.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18992.cnr -o NA18992.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18993.cnr -o NA18993.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18994.cnr -o NA18994.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18995.cnr -o NA18995.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18997.cnr -o NA18997.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18998.cnr -o NA18998.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA18999.cnr -o NA18999.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19000.cnr -o NA19000.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19001.cnr -o NA19001.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19002.cnr -o NA19002.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19003.cnr -o NA19003.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19004.cnr -o NA19004.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19005.cnr -o NA19005.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19006.cnr -o NA19006.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19007.cnr -o NA19007.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19009.cnr -o NA19009.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19010.cnr -o NA19010.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19011.cnr -o NA19011.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19012.cnr -o NA19012.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19017.cnr -o NA19017.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19019.cnr -o NA19019.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19020.cnr -o NA19020.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19023.cnr -o NA19023.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19024.cnr -o NA19024.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19025.cnr -o NA19025.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19026.cnr -o NA19026.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19027.cnr -o NA19027.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19028.cnr -o NA19028.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19030.cnr -o NA19030.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19031.cnr -o NA19031.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19035.cnr -o NA19035.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19036.cnr -o NA19036.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19037.cnr -o NA19037.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19038.cnr -o NA19038.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19041.cnr -o NA19041.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19042.cnr -o NA19042.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19043.cnr -o NA19043.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19054.cnr -o NA19054.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19055.cnr -o NA19055.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19056.cnr -o NA19056.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19057.cnr -o NA19057.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19058.cnr -o NA19058.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19059.cnr -o NA19059.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19060.cnr -o NA19060.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19062.cnr -o NA19062.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19063.cnr -o NA19063.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19064.cnr -o NA19064.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19065.cnr -o NA19065.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19066.cnr -o NA19066.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19067.cnr -o NA19067.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19068.cnr -o NA19068.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19070.cnr -o NA19070.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19072.cnr -o NA19072.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19074.cnr -o NA19074.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19075.cnr -o NA19075.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19076.cnr -o NA19076.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19077.cnr -o NA19077.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19078.cnr -o NA19078.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19079.cnr -o NA19079.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19080.cnr -o NA19080.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19081.cnr -o NA19081.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19082.cnr -o NA19082.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19083.cnr -o NA19083.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19084.cnr -o NA19084.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19085.cnr -o NA19085.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19086.cnr -o NA19086.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19087.cnr -o NA19087.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19088.cnr -o NA19088.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19089.cnr -o NA19089.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19090.cnr -o NA19090.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19091.cnr -o NA19091.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19092.cnr -o NA19092.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19093.cnr -o NA19093.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19095.cnr -o NA19095.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19096.cnr -o NA19096.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19098.cnr -o NA19098.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19099.cnr -o NA19099.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19102.cnr -o NA19102.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19107.cnr -o NA19107.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19108.cnr -o NA19108.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19113.cnr -o NA19113.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19114.cnr -o NA19114.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19116.cnr -o NA19116.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19117.cnr -o NA19117.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19118.cnr -o NA19118.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19119.cnr -o NA19119.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19121.cnr -o NA19121.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19129.cnr -o NA19129.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19130.cnr -o NA19130.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19131.cnr -o NA19131.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19137.cnr -o NA19137.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19138.cnr -o NA19138.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19141.cnr -o NA19141.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19143.cnr -o NA19143.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19144.cnr -o NA19144.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19146.cnr -o NA19146.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19147.cnr -o NA19147.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19149.cnr -o NA19149.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19152.cnr -o NA19152.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19153.cnr -o NA19153.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19159.cnr -o NA19159.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19160.cnr -o NA19160.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19171.cnr -o NA19171.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19172.cnr -o NA19172.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19175.cnr -o NA19175.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19184.cnr -o NA19184.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19185.cnr -o NA19185.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19189.cnr -o NA19189.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19190.cnr -o NA19190.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19197.cnr -o NA19197.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19198.cnr -o NA19198.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19200.cnr -o NA19200.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19201.cnr -o NA19201.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19204.cnr -o NA19204.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19206.cnr -o NA19206.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19207.cnr -o NA19207.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19209.cnr -o NA19209.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19210.cnr -o NA19210.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19213.cnr -o NA19213.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19214.cnr -o NA19214.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19222.cnr -o NA19222.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19223.cnr -o NA19223.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19225.cnr -o NA19225.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19235.cnr -o NA19235.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19236.cnr -o NA19236.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19238.cnr -o NA19238.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19239.cnr -o NA19239.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19240.cnr -o NA19240.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19247.cnr -o NA19247.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19248.cnr -o NA19248.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19256.cnr -o NA19256.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19257.cnr -o NA19257.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19307.cnr -o NA19307.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19308.cnr -o NA19308.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19309.cnr -o NA19309.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19310.cnr -o NA19310.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19311.cnr -o NA19311.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19312.cnr -o NA19312.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19313.cnr -o NA19313.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19314.cnr -o NA19314.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19315.cnr -o NA19315.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19316.cnr -o NA19316.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19317.cnr -o NA19317.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19318.cnr -o NA19318.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19319.cnr -o NA19319.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19320.cnr -o NA19320.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19321.cnr -o NA19321.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19323.cnr -o NA19323.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19324.cnr -o NA19324.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19327.cnr -o NA19327.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19328.cnr -o NA19328.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19331.cnr -o NA19331.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19332.cnr -o NA19332.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19334.cnr -o NA19334.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19338.cnr -o NA19338.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19346.cnr -o NA19346.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19347.cnr -o NA19347.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19350.cnr -o NA19350.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19351.cnr -o NA19351.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19355.cnr -o NA19355.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19360.cnr -o NA19360.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19372.cnr -o NA19372.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19374.cnr -o NA19374.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19375.cnr -o NA19375.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19376.cnr -o NA19376.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19377.cnr -o NA19377.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19378.cnr -o NA19378.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19379.cnr -o NA19379.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19380.cnr -o NA19380.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19383.cnr -o NA19383.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19384.cnr -o NA19384.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19385.cnr -o NA19385.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19390.cnr -o NA19390.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19391.cnr -o NA19391.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19393.cnr -o NA19393.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19394.cnr -o NA19394.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19395.cnr -o NA19395.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19397.cnr -o NA19397.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19399.cnr -o NA19399.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19401.cnr -o NA19401.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19403.cnr -o NA19403.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19404.cnr -o NA19404.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19428.cnr -o NA19428.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19429.cnr -o NA19429.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19430.cnr -o NA19430.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19431.cnr -o NA19431.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19434.cnr -o NA19434.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19435.cnr -o NA19435.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19436.cnr -o NA19436.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19437.cnr -o NA19437.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19438.cnr -o NA19438.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19439.cnr -o NA19439.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19440.cnr -o NA19440.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19443.cnr -o NA19443.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19445.cnr -o NA19445.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19446.cnr -o NA19446.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19448.cnr -o NA19448.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19449.cnr -o NA19449.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19451.cnr -o NA19451.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19452.cnr -o NA19452.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19454.cnr -o NA19454.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19455.cnr -o NA19455.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19456.cnr -o NA19456.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19457.cnr -o NA19457.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19461.cnr -o NA19461.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19462.cnr -o NA19462.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19463.cnr -o NA19463.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19466.cnr -o NA19466.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19467.cnr -o NA19467.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19468.cnr -o NA19468.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19471.cnr -o NA19471.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19472.cnr -o NA19472.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19473.cnr -o NA19473.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19474.cnr -o NA19474.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19475.cnr -o NA19475.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19625.cnr -o NA19625.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19648.cnr -o NA19648.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19649.cnr -o NA19649.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19651.cnr -o NA19651.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19652.cnr -o NA19652.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19654.cnr -o NA19654.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19655.cnr -o NA19655.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19657.cnr -o NA19657.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19658.cnr -o NA19658.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19660.cnr -o NA19660.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19661.cnr -o NA19661.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19663.cnr -o NA19663.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19664.cnr -o NA19664.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19669.cnr -o NA19669.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19670.cnr -o NA19670.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19675.cnr -o NA19675.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19676.cnr -o NA19676.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19678.cnr -o NA19678.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19679.cnr -o NA19679.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19681.cnr -o NA19681.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19682.cnr -o NA19682.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19684.cnr -o NA19684.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19685.cnr -o NA19685.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19700.cnr -o NA19700.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19701.cnr -o NA19701.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19703.cnr -o NA19703.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19704.cnr -o NA19704.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19707.cnr -o NA19707.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19711.cnr -o NA19711.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19712.cnr -o NA19712.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19713.cnr -o NA19713.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19716.cnr -o NA19716.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19717.cnr -o NA19717.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19719.cnr -o NA19719.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19720.cnr -o NA19720.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19722.cnr -o NA19722.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19723.cnr -o NA19723.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19725.cnr -o NA19725.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19726.cnr -o NA19726.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19728.cnr -o NA19728.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19729.cnr -o NA19729.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19731.cnr -o NA19731.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19732.cnr -o NA19732.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19734.cnr -o NA19734.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19735.cnr -o NA19735.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19740.cnr -o NA19740.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19741.cnr -o NA19741.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19746.cnr -o NA19746.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19747.cnr -o NA19747.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19749.cnr -o NA19749.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19750.cnr -o NA19750.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19752.cnr -o NA19752.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19755.cnr -o NA19755.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19756.cnr -o NA19756.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19758.cnr -o NA19758.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19759.cnr -o NA19759.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19761.cnr -o NA19761.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19762.cnr -o NA19762.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19764.cnr -o NA19764.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19770.cnr -o NA19770.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19771.cnr -o NA19771.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19773.cnr -o NA19773.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19774.cnr -o NA19774.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19776.cnr -o NA19776.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19777.cnr -o NA19777.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19779.cnr -o NA19779.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19780.cnr -o NA19780.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19782.cnr -o NA19782.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19783.cnr -o NA19783.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19785.cnr -o NA19785.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19786.cnr -o NA19786.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19788.cnr -o NA19788.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19789.cnr -o NA19789.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19792.cnr -o NA19792.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19794.cnr -o NA19794.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19795.cnr -o NA19795.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19818.cnr -o NA19818.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19819.cnr -o NA19819.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19834.cnr -o NA19834.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19835.cnr -o NA19835.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19900.cnr -o NA19900.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19901.cnr -o NA19901.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19904.cnr -o NA19904.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19908.cnr -o NA19908.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19909.cnr -o NA19909.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19913.cnr -o NA19913.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19914.cnr -o NA19914.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19916.cnr -o NA19916.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19917.cnr -o NA19917.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19920.cnr -o NA19920.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19921.cnr -o NA19921.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19922.cnr -o NA19922.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19923.cnr -o NA19923.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19982.cnr -o NA19982.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19984.cnr -o NA19984.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA19985.cnr -o NA19985.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20126.cnr -o NA20126.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20127.cnr -o NA20127.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20274.cnr -o NA20274.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20276.cnr -o NA20276.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20278.cnr -o NA20278.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20281.cnr -o NA20281.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20282.cnr -o NA20282.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20287.cnr -o NA20287.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20289.cnr -o NA20289.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20291.cnr -o NA20291.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20294.cnr -o NA20294.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20296.cnr -o NA20296.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20298.cnr -o NA20298.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20299.cnr -o NA20299.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20314.cnr -o NA20314.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20317.cnr -o NA20317.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20318.cnr -o NA20318.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20320.cnr -o NA20320.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20321.cnr -o NA20321.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20322.cnr -o NA20322.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20332.cnr -o NA20332.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20334.cnr -o NA20334.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20336.cnr -o NA20336.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20339.cnr -o NA20339.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20340.cnr -o NA20340.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20341.cnr -o NA20341.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20342.cnr -o NA20342.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20344.cnr -o NA20344.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20346.cnr -o NA20346.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20348.cnr -o NA20348.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20351.cnr -o NA20351.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20355.cnr -o NA20355.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20356.cnr -o NA20356.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20357.cnr -o NA20357.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20359.cnr -o NA20359.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20362.cnr -o NA20362.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20412.cnr -o NA20412.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20502.cnr -o NA20502.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20503.cnr -o NA20503.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20504.cnr -o NA20504.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20505.cnr -o NA20505.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20506.cnr -o NA20506.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20507.cnr -o NA20507.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20508.cnr -o NA20508.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20509.cnr -o NA20509.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20510.cnr -o NA20510.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20511.cnr -o NA20511.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20512.cnr -o NA20512.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20513.cnr -o NA20513.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20514.cnr -o NA20514.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20515.cnr -o NA20515.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20516.cnr -o NA20516.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20517.cnr -o NA20517.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20518.cnr -o NA20518.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20519.cnr -o NA20519.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20520.cnr -o NA20520.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20521.cnr -o NA20521.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20522.cnr -o NA20522.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20524.cnr -o NA20524.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20525.cnr -o NA20525.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20526.cnr -o NA20526.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20527.cnr -o NA20527.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20528.cnr -o NA20528.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20529.cnr -o NA20529.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20530.cnr -o NA20530.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20531.cnr -o NA20531.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20532.cnr -o NA20532.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20533.cnr -o NA20533.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20534.cnr -o NA20534.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20535.cnr -o NA20535.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20536.cnr -o NA20536.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20538.cnr -o NA20538.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20539.cnr -o NA20539.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20540.cnr -o NA20540.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20541.cnr -o NA20541.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20542.cnr -o NA20542.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20543.cnr -o NA20543.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20544.cnr -o NA20544.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20581.cnr -o NA20581.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20582.cnr -o NA20582.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20585.cnr -o NA20585.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20586.cnr -o NA20586.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20587.cnr -o NA20587.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20588.cnr -o NA20588.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20589.cnr -o NA20589.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20752.cnr -o NA20752.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20753.cnr -o NA20753.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20754.cnr -o NA20754.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20755.cnr -o NA20755.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20756.cnr -o NA20756.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20757.cnr -o NA20757.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20758.cnr -o NA20758.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20759.cnr -o NA20759.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20760.cnr -o NA20760.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20761.cnr -o NA20761.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20762.cnr -o NA20762.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20763.cnr -o NA20763.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20764.cnr -o NA20764.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20765.cnr -o NA20765.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20766.cnr -o NA20766.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20767.cnr -o NA20767.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20768.cnr -o NA20768.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20769.cnr -o NA20769.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20770.cnr -o NA20770.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20771.cnr -o NA20771.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20772.cnr -o NA20772.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20773.cnr -o NA20773.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20774.cnr -o NA20774.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20775.cnr -o NA20775.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20778.cnr -o NA20778.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20783.cnr -o NA20783.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20785.cnr -o NA20785.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20786.cnr -o NA20786.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20787.cnr -o NA20787.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20790.cnr -o NA20790.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20792.cnr -o NA20792.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20795.cnr -o NA20795.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20796.cnr -o NA20796.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20797.cnr -o NA20797.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20798.cnr -o NA20798.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20799.cnr -o NA20799.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20802.cnr -o NA20802.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20803.cnr -o NA20803.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20804.cnr -o NA20804.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20805.cnr -o NA20805.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20806.cnr -o NA20806.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20807.cnr -o NA20807.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20808.cnr -o NA20808.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20809.cnr -o NA20809.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20810.cnr -o NA20810.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20811.cnr -o NA20811.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20812.cnr -o NA20812.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20813.cnr -o NA20813.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20814.cnr -o NA20814.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20815.cnr -o NA20815.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20818.cnr -o NA20818.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20819.cnr -o NA20819.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20821.cnr -o NA20821.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20822.cnr -o NA20822.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20826.cnr -o NA20826.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20827.cnr -o NA20827.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20828.cnr -o NA20828.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20832.cnr -o NA20832.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20845.cnr -o NA20845.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20846.cnr -o NA20846.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20847.cnr -o NA20847.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20849.cnr -o NA20849.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20850.cnr -o NA20850.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20851.cnr -o NA20851.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20852.cnr -o NA20852.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20853.cnr -o NA20853.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20854.cnr -o NA20854.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20856.cnr -o NA20856.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20858.cnr -o NA20858.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20859.cnr -o NA20859.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20861.cnr -o NA20861.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20862.cnr -o NA20862.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20863.cnr -o NA20863.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20864.cnr -o NA20864.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20866.cnr -o NA20866.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20867.cnr -o NA20867.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20868.cnr -o NA20868.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20869.cnr -o NA20869.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20870.cnr -o NA20870.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20871.cnr -o NA20871.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20872.cnr -o NA20872.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20874.cnr -o NA20874.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20875.cnr -o NA20875.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20876.cnr -o NA20876.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20877.cnr -o NA20877.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20878.cnr -o NA20878.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20881.cnr -o NA20881.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20882.cnr -o NA20882.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20884.cnr -o NA20884.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20885.cnr -o NA20885.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20886.cnr -o NA20886.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20887.cnr -o NA20887.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20888.cnr -o NA20888.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20889.cnr -o NA20889.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20890.cnr -o NA20890.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20891.cnr -o NA20891.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20892.cnr -o NA20892.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20893.cnr -o NA20893.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20894.cnr -o NA20894.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20895.cnr -o NA20895.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20896.cnr -o NA20896.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20897.cnr -o NA20897.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20898.cnr -o NA20898.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20899.cnr -o NA20899.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20900.cnr -o NA20900.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20901.cnr -o NA20901.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20902.cnr -o NA20902.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20903.cnr -o NA20903.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20904.cnr -o NA20904.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20905.cnr -o NA20905.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20906.cnr -o NA20906.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20908.cnr -o NA20908.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20910.cnr -o NA20910.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA20911.cnr -o NA20911.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21086.cnr -o NA21086.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21087.cnr -o NA21087.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21088.cnr -o NA21088.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21089.cnr -o NA21089.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21090.cnr -o NA21090.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21091.cnr -o NA21091.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21092.cnr -o NA21092.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21093.cnr -o NA21093.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21094.cnr -o NA21094.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21095.cnr -o NA21095.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21097.cnr -o NA21097.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21098.cnr -o NA21098.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21099.cnr -o NA21099.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21100.cnr -o NA21100.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21101.cnr -o NA21101.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21102.cnr -o NA21102.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21103.cnr -o NA21103.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21104.cnr -o NA21104.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21105.cnr -o NA21105.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21106.cnr -o NA21106.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21107.cnr -o NA21107.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21108.cnr -o NA21108.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21109.cnr -o NA21109.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21110.cnr -o NA21110.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21111.cnr -o NA21111.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21112.cnr -o NA21112.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21113.cnr -o NA21113.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21114.cnr -o NA21114.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21115.cnr -o NA21115.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21116.cnr -o NA21116.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21117.cnr -o NA21117.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21118.cnr -o NA21118.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21119.cnr -o NA21119.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21120.cnr -o NA21120.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21122.cnr -o NA21122.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21123.cnr -o NA21123.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21124.cnr -o NA21124.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21125.cnr -o NA21125.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21126.cnr -o NA21126.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21127.cnr -o NA21127.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21128.cnr -o NA21128.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21129.cnr -o NA21129.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21130.cnr -o NA21130.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21133.cnr -o NA21133.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21135.cnr -o NA21135.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21137.cnr -o NA21137.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21141.cnr -o NA21141.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21142.cnr -o NA21142.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21143.cnr -o NA21143.cns -m haar
docker run --rm -it -v /tmp:/tmp -w /tmp etal/cnvkit cnvkit.py segment NA21144.cnr -o NA21144.cns -m haar

